name: skeleton_lora_fe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - transformers
  - peft
  - safetensors
  - tensorboard
  - pandas
  - pyyaml
  - sentencepiece
  - protobuf
  - pip:
      - --index-url https://download.pytorch.org/whl/cu128
      - torch==2.11.0
